.TH "TREEKIN" "1" "" "" ""
.SH "NAME"
.LP 
\fBtreekin\fR \- Calculate a macrostate dynamics of biopolymers
.SH "SYNTAX"
.LP 
\fBtreekin\fR [\fIoptions\fP] < \fIfoo.bar\fP
.SH "DESCRIPTION"
.LP 
\fBtreekin\fR computes a reduced dynamics of biopolymer folding by means of numeric integration of a Markov process that generally operates at the level of macrostates, i.e. basins of attraction of the underlying energy landscape.
.br 
\fBtreekin\fR expects a .bar file via stdin, and optionally a rates file in the current working directory. Both the .bar file and the rates file (default name is \fIrates.out\fR) can be obtained from \fBbarriers\fR.
.SH "OPTIONS"
.LP 
.TP 
\fB\-a, \-\-absorb i\fR
Make a state \fIi\fR absorbing (default: none)
.TP 
\fB\-m, \-\-method m\fR
Select method to build transition matrix. Possible values for \fIm\fR are:
.br 
A ==> Arrhenius\-like macrostate kinetics (this is the default)
.br 
F ==> Full process kinetics (consider all states from subopt)
.br 
I ==> Apply microscrates from barriers (requires a rates file)
.TP 
\fB     \-\-p0 s=x\fR
Set the start population probability of state \fIs\fR to \fIx\fR. This option can be given multiple times. Please note that the individual population probabilities given here \fImust\fR sum up to 1.
.TP 
\fB     \-\-t0 time\fR
Set simulation start time in internal units (default: 0.1)
.TP 
\fB     \-\-t8 time\fR
Set simulation stop time in internal units (default: 1e+09)
.TP 
\fB     \-\-tinc increment\fR
Time scaling factor for logarithmic time scale (default: 1.02)
.TP 
\fB\-T,  \-\-Temp temp\fR
Set the simulation temperature in Celsius to \fItemp\fR (default: 37.0)
.TP 
\fB     \-\-info\fR
Show all settings (default: off)
.TP 
\fB\-f, \-\-ratesfile file\fR
Name of the text file containing the rates matrix as computed by \fBbarriers\fR. Individual rates in this file are expected in '%10.4g' format.
.TP 
\fB\-h \-\-help\fR
Output help information and exit.
.TP 
\fB\-V \-\-version\fR
Output version information and exit.
.SH "EXPERIMENTAL OPTIONS"
.LP 
.TP 
\fB\-b, \-\-bin\fR
Read binary input  (default: off)
.TP 
\fB\-d, \-\-degeneracy\fR
Consider degeracy in transition rates  (default: off)
.TP 
\fB\-e, \-\-exponent\fR
Solve the underlying differential equations by computing matrix exponentionals directly, hence no diagonalization is performed in this case. Please note that this option is only applicable to small matrices. (default: off)
.TP 
\fB    \-\-fpt\fR
Compute first passage times  (default: off)
.TP 
\fB\-n, \-\-nstates num\fR
Read \fInum\fR states (default: read all states)
.TP 
\fB\-r, \-\-recover\fR
Recover from pre\-calculated Eigenvalues and Eigenvectors (default: off)
.TP 
\fB\-w \-\-wrecover\fR
Write recovery file containing Eigenvalues and Eigenvectors (default: off)
.TP 
\fB\-u, \-\-umatrix\fR
Dump transition matrix U to a binary file mx.bin (default: off)
.TP 
\fB\-x, \-\-mathematicamatrix\fR
Dump transition matrix U to Mathematica\-readable file mxMat.txt  (default: off)
.SH "EXAMPLES"
.LP 
Typically, computation of a reduced dynamics based on the analysis of folding landscapes requires two steps: Elucidation of the landscape (topology) and \- based on that \- calculation of the reduced dynamics.

The first step involves computing the relevant properties of an energy landscape by \fBbarriers\fR (see \fBbarriers\fR(1) for details). The resulting .bar\-file contains information on local minima, basins, saddle points as well as thermodynamic properties of the energy landscape. Additionally, the \-\-rates option in the below example triggers \fBbarriers\fR to generate another output file (rates.out) containing the transition rates between all pairs of macrostates (ie. basins of attraction), calculated by summing over the corresponding microscopic rates. 
.LP 
barriers \-\-saddle \-\-bsize \-\-rates < foo.sub > foo.bar
.LP 
In a second step, \fBtreekin\fR is called with options to calculate the macrostate dynamics on the previously generated landscape by means of applying microscopic transition rates (option \-m I):
.LP 
treekin \-\-p0 2=1 \-m I < foo.bar
.LP 
In this example, the simulation starts with 100% of the initial population in macrostate 2, i.e. the second lowest minimum in the barrier tree (option \-\-p0 2=1).  The transition matrix is computed from a set of microscopic rates, read from a rates file (as computed by \fBbarriers\fR).

Generally, calculation of the macrostate dynamics by means of microscopic rates (option \-m I) is consiberably more accurate than the simplified Arrhenius\-like dynamics (option \-m A). 
.LP 
Looking at the default output produced by \fBtreekin\fR, there are two sections: Overall status information on the computation (marked by hash signs at the beginning of the line) are printed at the top. Below, the actual data is printed for each time step in (n+1) space\-separated columns, where n is the number of investigated (macro)states. The first column lists the current time, whereas all remaining columns correspond to the population probabilities of individual (macro)states.
.SH "REFERENCES"
If you use this program in your work you might want to cite the following original papers:
.LP 
M.T. Wolfinger, W.A. Svrcek\-Seiler, Ch. Flamm, I.L. Hofacker, P.F. Stadler
.br 
Efficient computation of RNA folding dynamics
.br 
J.Phys.A: Math.Gen. 37: 4731\-4741 (2004)
.LP 
I.L. Hofacker, Ch. Flamm, Ch. Heine, M.T. Wolfinger, G. Scheuermann, P.F. Stadler
.br 
BarMap: RNA folding on dynamic energy landscapes
.br 
RNA: 2010 16: 1308\-1316 (2010)
.SH "AUTHORS"
.LP 
Michael T. Wolfinger, Ivo Hofacker, Christoph Flamm, Andreas Svrcek\-Sailer, Peter Stadler.
.br 
Send comments to <ivo@tbi.univie.ac.at>
.SH "SEE ALSO"
.LP 
\fBbarriers\fR(1)
