/*
  File autogenerated by gengetopt version 2.18
  generated with the following command:
  gengetopt --file=treekin_cmdline --unamed-opts 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "treekin_cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: " CMDLINE_PARSER_PACKAGE " [OPTIONS]... [FILES]...";

const char *gengetopt_args_info_help[] = {
  "  -h, --help               Print help and exit",
  "  -V, --version            Print version and exit",
  "  -a, --absorb=state       Make a state absorbing",
  "  -m, --method=STRING      Select method to build transition matrix:\n                             A ==>Arrhenius-like kinetics\n                             F ==> Full process kinetics (whole subopt)\n                             I==>use rates from barriers  (possible \n                             values=\"A\", \"F\", \"I\" default=`A')",
  "      --t0=time            Start time",
  "      --t8=time            Stop time",
  "  -T, --Temp=DOUBLE        Temperatur in Celsius",
  "  -n, --nstates=INT        Read <int> states",
  "      --p0=STRING          Set initial population of state <int> to <double>\n                             Can be given multiple times\n                             (NOTE: sum of <double> must equal 1)",
  "      --tinc=DOUBLE        Time scaling factor (for log time-scale)",
  "  -d, --degeneracy         Consider degeracy in transition rates  (default=off)",
  "  -e, --exponent           Use matrix-expontent routines, NO diagonalization  \n                             (default=off)",
  "  -u, --umatrix            Dump transition matrix U to a binary file mx.bin  \n                             (default=off)",
  "  -x, --mathematicamatrix  Dump transition matrix U to Mathematica-readable \n                             file mxMat.txt  (default=off)",
  "      --info               show settings  (default=off)",
  "  -v, --verbose            verbose output  (default=off)",
  "  -b, --bin                assume binary input  (default=off)",
  "      --fpt                calculate first passage times  (default=off)",
    0
};

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

struct string_list
{
  char * arg;
  char *orig;
  struct string_list * next;
};

char *cmdline_parser_method_values[] = {"A", "F", "I", 0} ;	/* Possible values for method.  */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->absorb_given = 0 ;
  args_info->method_given = 0 ;
  args_info->t0_given = 0 ;
  args_info->t8_given = 0 ;
  args_info->Temp_given = 0 ;
  args_info->nstates_given = 0 ;
  args_info->p0_given = 0 ;
  args_info->tinc_given = 0 ;
  args_info->degeneracy_given = 0 ;
  args_info->exponent_given = 0 ;
  args_info->umatrix_given = 0 ;
  args_info->mathematicamatrix_given = 0 ;
  args_info->info_given = 0 ;
  args_info->verbose_given = 0 ;
  args_info->bin_given = 0 ;
  args_info->fpt_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->absorb_orig = NULL;
  args_info->method_arg = gengetopt_strdup ("A");
  args_info->method_orig = NULL;
  args_info->t0_orig = NULL;
  args_info->t8_orig = NULL;
  args_info->Temp_orig = NULL;
  args_info->nstates_orig = NULL;
  args_info->p0_arg = NULL;
  args_info->p0_orig = NULL;
  args_info->tinc_orig = NULL;
  args_info->degeneracy_flag = 0;
  args_info->exponent_flag = 0;
  args_info->umatrix_flag = 0;
  args_info->mathematicamatrix_flag = 0;
  args_info->info_flag = 0;
  args_info->verbose_flag = 0;
  args_info->bin_flag = 0;
  args_info->fpt_flag = 0;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{
  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->absorb_help = gengetopt_args_info_help[2] ;
  args_info->method_help = gengetopt_args_info_help[3] ;
  args_info->t0_help = gengetopt_args_info_help[4] ;
  args_info->t8_help = gengetopt_args_info_help[5] ;
  args_info->Temp_help = gengetopt_args_info_help[6] ;
  args_info->nstates_help = gengetopt_args_info_help[7] ;
  args_info->p0_help = gengetopt_args_info_help[8] ;
  args_info->p0_min = -1;
  args_info->p0_max = -1;
  args_info->tinc_help = gengetopt_args_info_help[9] ;
  args_info->degeneracy_help = gengetopt_args_info_help[10] ;
  args_info->exponent_help = gengetopt_args_info_help[11] ;
  args_info->umatrix_help = gengetopt_args_info_help[12] ;
  args_info->mathematicamatrix_help = gengetopt_args_info_help[13] ;
  args_info->info_help = gengetopt_args_info_help[14] ;
  args_info->verbose_help = gengetopt_args_info_help[15] ;
  args_info->bin_help = gengetopt_args_info_help[16] ;
  args_info->fpt_help = gengetopt_args_info_help[17] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  printf("\n%s\n\n", gengetopt_args_info_usage);
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = NULL;
  args_info->inputs_num = 0;
}

static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  
  unsigned int i;
  if (args_info->absorb_orig)
    {
      free (args_info->absorb_orig); /* free previous argument */
      args_info->absorb_orig = 0;
    }
  if (args_info->method_arg)
    {
      free (args_info->method_arg); /* free previous argument */
      args_info->method_arg = 0;
    }
  if (args_info->method_orig)
    {
      free (args_info->method_orig); /* free previous argument */
      args_info->method_orig = 0;
    }
  if (args_info->t0_orig)
    {
      free (args_info->t0_orig); /* free previous argument */
      args_info->t0_orig = 0;
    }
  if (args_info->t8_orig)
    {
      free (args_info->t8_orig); /* free previous argument */
      args_info->t8_orig = 0;
    }
  if (args_info->Temp_orig)
    {
      free (args_info->Temp_orig); /* free previous argument */
      args_info->Temp_orig = 0;
    }
  if (args_info->nstates_orig)
    {
      free (args_info->nstates_orig); /* free previous argument */
      args_info->nstates_orig = 0;
    }
  if (args_info->p0_arg)
    {
      for (i = 0; i < args_info->p0_given; ++i)
        {
          if (args_info->p0_arg [i])
            {
              free (args_info->p0_arg [i]); /* free previous argument */
              args_info->p0_arg [i] = 0;
            }
          if (args_info->p0_orig [i])
            {
              free (args_info->p0_orig [i]); /* free previous argument */
              args_info->p0_orig [i] = 0;
            }
        }
      if (args_info->p0_arg [0])
        free (args_info->p0_arg [0]); /* free default string */
      free (args_info->p0_arg); /* free previous argument */
      args_info->p0_arg = 0;
      free (args_info->p0_orig); /* free previous argument */
      args_info->p0_orig = 0;
    }
  if (args_info->tinc_orig)
    {
      free (args_info->tinc_orig); /* free previous argument */
      args_info->tinc_orig = 0;
    }
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);
  
  if (args_info->inputs_num)
    free (args_info->inputs);
  
  clear_given (args_info);
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  if (args_info->help_given) {
    fprintf(outfile, "%s\n", "help");
  }
  if (args_info->version_given) {
    fprintf(outfile, "%s\n", "version");
  }
  if (args_info->absorb_given) {
    if (args_info->absorb_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "absorb", args_info->absorb_orig);
    } else {
      fprintf(outfile, "%s\n", "absorb");
    }
  }
  if (args_info->method_given) {
    if (args_info->method_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "method", args_info->method_orig);
    } else {
      fprintf(outfile, "%s\n", "method");
    }
  }
  if (args_info->t0_given) {
    if (args_info->t0_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "t0", args_info->t0_orig);
    } else {
      fprintf(outfile, "%s\n", "t0");
    }
  }
  if (args_info->t8_given) {
    if (args_info->t8_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "t8", args_info->t8_orig);
    } else {
      fprintf(outfile, "%s\n", "t8");
    }
  }
  if (args_info->Temp_given) {
    if (args_info->Temp_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "Temp", args_info->Temp_orig);
    } else {
      fprintf(outfile, "%s\n", "Temp");
    }
  }
  if (args_info->nstates_given) {
    if (args_info->nstates_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "nstates", args_info->nstates_orig);
    } else {
      fprintf(outfile, "%s\n", "nstates");
    }
  }
  if (args_info->p0_orig)
    {
      for (i = 0; i < args_info->p0_given; ++i)
        {
          if (args_info->p0_orig [i])
            {
              fprintf(outfile, "%s=\"%s\"\n", "p0", args_info->p0_orig [i]);
            }
        }
    }
  if (args_info->tinc_given) {
    if (args_info->tinc_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "tinc", args_info->tinc_orig);
    } else {
      fprintf(outfile, "%s\n", "tinc");
    }
  }
  if (args_info->degeneracy_given) {
    fprintf(outfile, "%s\n", "degeneracy");
  }
  if (args_info->exponent_given) {
    fprintf(outfile, "%s\n", "exponent");
  }
  if (args_info->umatrix_given) {
    fprintf(outfile, "%s\n", "umatrix");
  }
  if (args_info->mathematicamatrix_given) {
    fprintf(outfile, "%s\n", "mathematicamatrix");
  }
  if (args_info->info_given) {
    fprintf(outfile, "%s\n", "info");
  }
  if (args_info->verbose_given) {
    fprintf(outfile, "%s\n", "verbose");
  }
  if (args_info->bin_given) {
    fprintf(outfile, "%s\n", "bin");
  }
  if (args_info->fpt_given) {
    fprintf(outfile, "%s\n", "fpt");
  }
  
  fclose (outfile);

  i = EXIT_SUCCESS;
  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/*
 * Returns:
 * - the index of the matched value
 * - -1 if no argument has been specified
 * - -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values are matched */
}


/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static char *
get_multiple_arg_token(const char *arg)
{
  char *tok, *ret;
  size_t len, num_of_escape;
  int i, j;

  if (!arg)
    return NULL;

  tok = strchr (arg, ',');
  num_of_escape = 0;

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
          ++num_of_escape;
        }
      else
        break;
    }

  if (tok)
    len = (size_t)(tok - arg + 1);
  else
    len = strlen (arg) + 1;

  len -= num_of_escape;

  ret = (char *) malloc (len);

  i = 0;
  j = 0;
  while (arg[i] && (j < len-1))
    {
      if (arg[i] == '\\')
        ++i;

      ret[j++] = arg[i++];
    }

  ret[len-1] = '\0';

  return ret;
}

static char *
get_multiple_arg_token_next(const char *arg)
{
  char *tok;

  if (!arg)
    return NULL;

  tok = strchr (arg, ',');

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
        }
      else
        break;
    }

  if (! tok || strlen(tok) == 1)
    return 0;

  return tok+1;
}

static int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, int min, int max, const char *option_desc);

int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, int min, int max, const char *option_desc)
{
  int error = 0;

  if (option_given && ! (min < 0 && max < 0))
    {
      if (min >= 0 && max >= 0)
        {
          if (min == max)
            {
              /* specific occurrences */
              if (option_given != min)
                {
                  fprintf (stderr, "%s: %s option occurrences must be %d\n",
                    prog_name, option_desc, min);
                  error = 1;
                }
            }
          else if (option_given < min
              || option_given > max)
            {
              /* range occurrences */
              fprintf (stderr, "%s: %s option occurrences must be between %d and %d\n",
                prog_name, option_desc, min, max);
              error = 1;
            }
        }
      else if (min >= 0)
        {
          /* at least check */
          if (option_given < min)
            {
              fprintf (stderr, "%s: %s option occurrences must be at least %d\n",
                prog_name, option_desc, min);
              error = 1;
            }
        }
      else if (max >= 0)
        {
          /* at most check */
          if (option_given > max)
            {
              fprintf (stderr, "%s: %s option occurrences must be at most %d\n",
                prog_name, option_desc, max);
              error = 1;
            }
        }
    }
    
  return error;
}
int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;

  result = cmdline_parser_internal (argc, argv, args_info, override, initialize, check_required, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, NULL) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;

  /* checks for required options */
  if (check_multiple_option_occurrences(prog_name, args_info->p0_given, args_info->p0_min, args_info->p0_max, "'--p0'"))
     error = 1;
  
  
  /* checks for dependences among options */

  return error;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */
  char *multi_token, *multi_next; /* for multiple options */

  int i;        /* Counter */

  struct string_list * p0_list = NULL,* p0_new = NULL;
  int error = 0;
  struct gengetopt_args_info local_args_info;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int found = 0;
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "absorb",	1, NULL, 'a' },
        { "method",	1, NULL, 'm' },
        { "t0",	1, NULL, 0 },
        { "t8",	1, NULL, 0 },
        { "Temp",	1, NULL, 'T' },
        { "nstates",	1, NULL, 'n' },
        { "p0",	1, NULL, 0 },
        { "tinc",	1, NULL, 0 },
        { "degeneracy",	0, NULL, 'd' },
        { "exponent",	0, NULL, 'e' },
        { "umatrix",	0, NULL, 'u' },
        { "mathematicamatrix",	0, NULL, 'x' },
        { "info",	0, NULL, 0 },
        { "verbose",	0, NULL, 'v' },
        { "bin",	0, NULL, 'b' },
        { "fpt",	0, NULL, 0 },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVa:m:T:n:deuxvb", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'a':	/* Make a state absorbing.  */
          if (local_args_info.absorb_given)
            {
              fprintf (stderr, "%s: `--absorb' (`-a') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->absorb_given && ! override)
            continue;
          local_args_info.absorb_given = 1;
          args_info->absorb_given = 1;
          args_info->absorb_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->absorb_orig)
            free (args_info->absorb_orig); /* free previous string */
          args_info->absorb_orig = gengetopt_strdup (optarg);
          break;

        case 'm':	/* Select method to build transition matrix:\nA ==>Arrhenius-like kinetics\nF ==> Full process kinetics (whole subopt)\nI==>use rates from barriers.  */
          if (local_args_info.method_given)
            {
              fprintf (stderr, "%s: `--method' (`-m') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if ((found = check_possible_values((optarg ? optarg : 0 ), cmdline_parser_method_values)) < 0)
            {
              fprintf (stderr, "%s: %s argument, \"%s\", for option `--method' (`-m')%s\n", argv[0], (found == -2) ? "ambiguous" : "invalid", optarg, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->method_given && ! override)
            continue;
          local_args_info.method_given = 1;
          args_info->method_given = 1;
          if (args_info->method_arg)
            free (args_info->method_arg); /* free previous string */
          args_info->method_arg = gengetopt_strdup (cmdline_parser_method_values[found]);
          if (args_info->method_orig)
            free (args_info->method_orig); /* free previous string */
          args_info->method_orig = gengetopt_strdup (optarg);
          break;

        case 'T':	/* Temperatur in Celsius.  */
          if (local_args_info.Temp_given)
            {
              fprintf (stderr, "%s: `--Temp' (`-T') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->Temp_given && ! override)
            continue;
          local_args_info.Temp_given = 1;
          args_info->Temp_given = 1;
          args_info->Temp_arg = strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->Temp_orig)
            free (args_info->Temp_orig); /* free previous string */
          args_info->Temp_orig = gengetopt_strdup (optarg);
          break;

        case 'n':	/* Read <int> states.  */
          if (local_args_info.nstates_given)
            {
              fprintf (stderr, "%s: `--nstates' (`-n') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->nstates_given && ! override)
            continue;
          local_args_info.nstates_given = 1;
          args_info->nstates_given = 1;
          args_info->nstates_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->nstates_orig)
            free (args_info->nstates_orig); /* free previous string */
          args_info->nstates_orig = gengetopt_strdup (optarg);
          break;

        case 'd':	/* Consider degeracy in transition rates.  */
          if (local_args_info.degeneracy_given)
            {
              fprintf (stderr, "%s: `--degeneracy' (`-d') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->degeneracy_given && ! override)
            continue;
          local_args_info.degeneracy_given = 1;
          args_info->degeneracy_given = 1;
          args_info->degeneracy_flag = !(args_info->degeneracy_flag);
          break;

        case 'e':	/* Use matrix-expontent routines, NO diagonalization.  */
          if (local_args_info.exponent_given)
            {
              fprintf (stderr, "%s: `--exponent' (`-e') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->exponent_given && ! override)
            continue;
          local_args_info.exponent_given = 1;
          args_info->exponent_given = 1;
          args_info->exponent_flag = !(args_info->exponent_flag);
          break;

        case 'u':	/* Dump transition matrix U to a binary file mx.bin.  */
          if (local_args_info.umatrix_given)
            {
              fprintf (stderr, "%s: `--umatrix' (`-u') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->umatrix_given && ! override)
            continue;
          local_args_info.umatrix_given = 1;
          args_info->umatrix_given = 1;
          args_info->umatrix_flag = !(args_info->umatrix_flag);
          break;

        case 'x':	/* Dump transition matrix U to Mathematica-readable file mxMat.txt.  */
          if (local_args_info.mathematicamatrix_given)
            {
              fprintf (stderr, "%s: `--mathematicamatrix' (`-x') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->mathematicamatrix_given && ! override)
            continue;
          local_args_info.mathematicamatrix_given = 1;
          args_info->mathematicamatrix_given = 1;
          args_info->mathematicamatrix_flag = !(args_info->mathematicamatrix_flag);
          break;

        case 'v':	/* verbose output.  */
          if (local_args_info.verbose_given)
            {
              fprintf (stderr, "%s: `--verbose' (`-v') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->verbose_given && ! override)
            continue;
          local_args_info.verbose_given = 1;
          args_info->verbose_given = 1;
          args_info->verbose_flag = !(args_info->verbose_flag);
          break;

        case 'b':	/* assume binary input.  */
          if (local_args_info.bin_given)
            {
              fprintf (stderr, "%s: `--bin' (`-b') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->bin_given && ! override)
            continue;
          local_args_info.bin_given = 1;
          args_info->bin_given = 1;
          args_info->bin_flag = !(args_info->bin_flag);
          break;


        case 0:	/* Long option with no short option */
          /* Start time.  */
          if (strcmp (long_options[option_index].name, "t0") == 0)
          {
            if (local_args_info.t0_given)
              {
                fprintf (stderr, "%s: `--t0' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->t0_given && ! override)
              continue;
            local_args_info.t0_given = 1;
            args_info->t0_given = 1;
            args_info->t0_arg = strtod (optarg, &stop_char);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->t0_orig)
              free (args_info->t0_orig); /* free previous string */
            args_info->t0_orig = gengetopt_strdup (optarg);
          }
          /* Stop time.  */
          else if (strcmp (long_options[option_index].name, "t8") == 0)
          {
            if (local_args_info.t8_given)
              {
                fprintf (stderr, "%s: `--t8' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->t8_given && ! override)
              continue;
            local_args_info.t8_given = 1;
            args_info->t8_given = 1;
            args_info->t8_arg = strtod (optarg, &stop_char);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->t8_orig)
              free (args_info->t8_orig); /* free previous string */
            args_info->t8_orig = gengetopt_strdup (optarg);
          }
          /* Set initial population of state <int> to <double>\nCan be given multiple times\n(NOTE: sum of <double> must equal 1).  */
          else if (strcmp (long_options[option_index].name, "p0") == 0)
          {
            local_args_info.p0_given++;
          
            multi_token = get_multiple_arg_token(optarg);
            multi_next = get_multiple_arg_token_next (optarg);
          
            while (1)
              {
                p0_new = (struct string_list *) malloc (sizeof (struct string_list));
                p0_new->next = p0_list;
                p0_list = p0_new;
                p0_new->arg = gengetopt_strdup (multi_token);
                p0_new->orig = multi_token;
          
                if (multi_next)
                  {
                    multi_token = get_multiple_arg_token(multi_next);
                    multi_next = get_multiple_arg_token_next (multi_next);
                    local_args_info.p0_given++;
                  }
                else
                  break;
              }
            break;
          }
          /* Time scaling factor (for log time-scale).  */
          else if (strcmp (long_options[option_index].name, "tinc") == 0)
          {
            if (local_args_info.tinc_given)
              {
                fprintf (stderr, "%s: `--tinc' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->tinc_given && ! override)
              continue;
            local_args_info.tinc_given = 1;
            args_info->tinc_given = 1;
            args_info->tinc_arg = strtod (optarg, &stop_char);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->tinc_orig)
              free (args_info->tinc_orig); /* free previous string */
            args_info->tinc_orig = gengetopt_strdup (optarg);
          }
          /* show settings.  */
          else if (strcmp (long_options[option_index].name, "info") == 0)
          {
            if (local_args_info.info_given)
              {
                fprintf (stderr, "%s: `--info' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->info_given && ! override)
              continue;
            local_args_info.info_given = 1;
            args_info->info_given = 1;
            args_info->info_flag = !(args_info->info_flag);
          }
          /* calculate first passage times.  */
          else if (strcmp (long_options[option_index].name, "fpt") == 0)
          {
            if (local_args_info.fpt_given)
              {
                fprintf (stderr, "%s: `--fpt' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->fpt_given && ! override)
              continue;
            local_args_info.fpt_given = 1;
            args_info->fpt_given = 1;
            args_info->fpt_flag = !(args_info->fpt_flag);
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */


  if (local_args_info.p0_given && p0_list)
    {
      struct string_list *tmp;
      args_info->p0_arg = (char * *) realloc (args_info->p0_arg, (args_info->p0_given + local_args_info.p0_given) * sizeof (char *));
      args_info->p0_orig = (char **) realloc (args_info->p0_orig, (args_info->p0_given + local_args_info.p0_given) * sizeof (char *));
      for (i = (local_args_info.p0_given - 1); i >= 0; --i)
        {
          tmp = p0_list;
          args_info->p0_arg [i + args_info->p0_given] = p0_list->arg;
          args_info->p0_orig [i + args_info->p0_given] = p0_list->orig;
          p0_list = p0_list->next;
          free (tmp);
        }
    }
  

  args_info->p0_given += local_args_info.p0_given;
  local_args_info.p0_given = 0;
  
  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  if (p0_list)
    {
      struct string_list *tmp;
      while (p0_list)
        {
          tmp = p0_list;
          free (p0_list->arg);
          free (p0_list->orig);
          p0_list = p0_list->next;
          free (tmp);
        }
    }
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
