.TH "TREEKIN" "1" "" "" ""
.SH "NAME"
.LP 
\fBtreekin\fR \- Calculate a macrostate dynamics of biopolymers
.SH "SYNTAX"
.LP 
treekin [\fIoptions\fP] < \fIfoo.bar\fP
.SH "DESCRIPTION"
.LP 
\fBtreekin\fR computes a reduced dynamics of biopolymer folding  by means
of a  Markov process that (generally) operates at the level of macrostates,
i.e. basins of attraction in the underlying energy landscapes.
.br 
\fBtreekin\fR reads a barfile \fIfoo.bar\fR  and (optionally) a file \fIrates.out\fR in the current working directory (as computed by \fBbarriers\fR).
.SH "OPTIONS"
.LP 
.TP 
\fB\-a, \-\-absorb i\fR
Make a state \fIi\fR absorbing (default none)
.TP 
\fB\-m, \-\-method m\fR
Select method to build transition matrix. Possible values for \fIm\fR are:
.br 
A ==> Arrhenius\-like macrostate kinetics (default)
.br 
F ==> Full process kinetics (consider all states from subopt)
.br 
I ==> Apply microscrates from barriers
.br 
      N.B.: A rates.out file must be present in the current working directory
.TP 
\fB     \-\-p0 s=x\fR
Set the start population probability of state \fIs\fR to \fIx\fR. This option can be given multiple times. Note that the sum of all population probabilities must be 1.
.TP 
\fB     \-\-t0 time\fR
Set simulation start time in internal units (default 0.1)
.TP 
\fB     \-\-t8 time\fR
Set simulation stop time in internal units (default 1e+09)
.TP 
\fB     \-\-tinc increment\fR
Time scaling factor for logarithmic time scale (default 1.02)
.TP 
\fB\-T,  \-\-Temp temp\fR
Set the simulation temperature in Celsius to \fItemp\fR (default 37.0)
.TP 
\fB     \-\-info\fR
Show all settings (default off)
.TP
\fB	\-f, \-\-ratesfile file
Name of the textfile containing the (barriers) rate matrix.
(NOTE: rates should have been printed using the '%10.4g' format).
.TP 
\fB\-h \-\-help\fR
Output help information and exit.
.TP 
\fB\-V \-\-version\fR
Output version information and exit.
.SH "EXPERIMENTAL OPTIONS"
.LP 
.TP 
\fB\-b, \-\-bin\fR
read binary input  (default= off)
.TP 
\fB\-d, \-\-degeneracy\fR
Consider degeracy in transition rates  (default= off)
.TP 
\fB\-e, \-\-exponent\fR
Use matrix\-expontent routines, NO diagonalization (default off)
.TP 
\fB    \-\-fpt\fR
calculate first passage times  (default=off)
.TP 
\fB\-n, \-\-nstates num\fR
Read \fInum\fR states
.TP 
\fB\-r, \-\-recover\fR
Recover from pre\-calculated Eigenvalues and Eigenvectors (default=off)
.TP 
\fB\-w \-\-wrecover\fR
Write recovery file containing Eigenvalues and Eigenvectors (default=off)
.TP 
\fB\-u, \-\-umatrix\fR
Dump transition matrix U to a binary file mx.bin (default= off)
.TP 
\fB\-x, \-\-mathematicamatrix\fR
Dump transition matrix U to Mathematica\-readable file mxMat.txt  (default=off)
.SH "EXAMPLES"
.LP 
Typically, the first step is to compute an energy landscape by barriers:
.LP 
barriers \-\-saddle \-\-bsize \-\-rates < foo.sub > foo.bar
.LP 
the resulting barfile (foo.bar) and rates file (rates.out) are then processed by:
.LP 
treekin \-\-p0 2=1 \-m I < foo.bar
.LP 
Here, the simulation starts with 100% of the initial population in
macrostate 2 (the second lowest minimum in the barrier tree). The transition matrix is constructed from a set of microscopic rates (as computed by \fBbarriers\fR). Generally, the microstate dynamics is much more accurate than the simple Arrhenius\-like dynamics. 
.br 
The first column in the output is the time, all other columns list the
population of the individual (macro)states of the simulation.
.SH "REFERENCES"
If you use this program in your work you might want to cite:
.LP 
M.T. Wolfinger, W.A. Svrcek\-Seiler, Ch. Flamm, I.L. Hofacker, P.F. Stadler (2004) Efficient Folding Dynamics of RNA Secondary Structures
J.Phys.A: Math.Gen. 37: 4731\-4741
.LP
I.L. Hofacker, Ch. Flamm, Ch. Heine, M.T. Wolfinger, G. Scheuermann,
P.F. Stadler (2010)
BarMap: RNA Folding on Dynamic Energy Landscapes
RNA (in press)
.SH "AUTHORS"
.LP 
Michael Wolfinger, Ivo Hofacker, Christoph Flamm, Andreas Svrcek\-Sailer, Peter Stadler. Send comments to <ivo@tbi.univie.ac.at>
.SH "SEE ALSO"
.LP 
\fBbarriers\fR(1)
